name: CMake

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake libsdl2-dev
    - name: Configure and build
      run: |
            mkdir build
            cmake -S .. -B build
            cd build 
            make